version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3308:3306"

  redis:
    image: redis:alpine
    ports:
      - "6378:6379"

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: crm
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
      - redis
    command: >
      sh -c "
        wait-for-it db:3306 -t 60 &&
        composer install &&
        php artisan cache:clear &&
        php artisan config:clear &&
        php artisan migrate --force &&
        php artisan db:seed --force &&
        php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend_new
    volumes:
      - ./frontend_new:/app
    command: sh -c "yarn install && yarn build"
    ports:
      - "5173:5173"

  frontend-nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend_new/dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro



volumes:
  db-data:
